"""
Topic-specific 5-question assessment banks.
Each topic has 5 questions for post-content assessment.
Questions are open-ended with model answers for scoring.
"""

TOPIC_QUESTIONS = {
    # ─── Playwright ───
    "pw-intro": [
        {"id": "pw-intro-1", "question": "What is Playwright and how does it differ from Selenium?", "keywords": ["microsoft", "browser", "chromium", "firefox", "webkit", "auto-wait", "multiple browsers"], "model_answer": "Playwright is a Microsoft open-source framework for web testing that supports Chromium, Firefox, and WebKit. Unlike Selenium, it has built-in auto-waiting, runs in a single process, supports multiple browser contexts, and offers better handling of modern web apps with native support for shadow DOM and iframes."},
        {"id": "pw-intro-2", "question": "Explain the concept of browser contexts in Playwright.", "keywords": ["isolation", "cookies", "session", "parallel", "independent", "incognito"], "model_answer": "Browser contexts are isolated browser sessions within a single browser instance. Each context has its own cookies, localStorage, and session state, similar to incognito profiles. They enable parallel test execution without interference and are lightweight compared to launching separate browsers."},
        {"id": "pw-intro-3", "question": "How do you set up a basic Playwright test project?", "keywords": ["install", "npm", "pip", "init", "config", "test runner", "browsers"], "model_answer": "Install Playwright via npm (npm init playwright@latest) or pip (pip install playwright). Run playwright install to download browsers. Configure playwright.config.ts/js with test directory, timeout, browser settings. Create test files with test() blocks using page fixture."},
        {"id": "pw-intro-4", "question": "What are the key advantages of Playwright's auto-waiting mechanism?", "keywords": ["wait", "actionability", "visible", "enabled", "stable", "flaky", "retry"], "model_answer": "Playwright auto-waits for elements to be actionable before performing operations. It checks visibility, enabled state, and stability automatically. This eliminates explicit waits, reduces flaky tests, and makes tests more reliable. The built-in retry mechanism handles dynamic content loading naturally."},
        {"id": "pw-intro-5", "question": "Describe the Playwright test runner and its key features.", "keywords": ["parallel", "fixtures", "hooks", "reporter", "retry", "trace", "screenshot"], "model_answer": "Playwright Test runner supports parallel execution, test fixtures for setup/teardown, beforeEach/afterEach hooks, multiple reporters (HTML, JSON, JUnit), automatic retries on failure, trace viewer for debugging, and screenshot/video capture on failure."},
    ],
    "pw-selectors": [
        {"id": "pw-sel-1", "question": "What are the different types of selectors in Playwright?", "keywords": ["css", "xpath", "text", "role", "data-testid", "locator"], "model_answer": "Playwright supports CSS selectors, XPath, text selectors (text=), role-based selectors (role=button), data-testid attributes, and chained/filtered locators. Role-based and text selectors are recommended for resilient tests."},
        {"id": "pw-sel-2", "question": "Why are role-based selectors recommended in Playwright?", "keywords": ["accessibility", "resilient", "semantic", "aria", "user-facing", "readable"], "model_answer": "Role-based selectors use ARIA roles reflecting how users perceive the page. They are resilient to DOM changes, improve test readability, align with accessibility best practices, and test the application the way users interact with it."},
        {"id": "pw-sel-3", "question": "How does the Playwright locator API differ from element handles?", "keywords": ["strict", "auto-wait", "lazy", "retry", "chainable", "filtering"], "model_answer": "Locators are strict (fail if multiple matches), support auto-waiting, are lazily evaluated (re-query on each action), support chaining and filtering. Element handles are snapshots that can go stale. Locators are the recommended approach."},
        {"id": "pw-sel-4", "question": "Explain how to use locator filtering and chaining.", "keywords": ["filter", "has", "hasText", "nth", "first", "last", "chain"], "model_answer": "Locators can be filtered with .filter({hasText: 'text'}), .filter({has: childLocator}), narrowed with .nth(0), .first(), .last(). Chain locators with .locator() to scope within results: page.locator('.list').locator('.item').filter({hasText: 'active'})."},
        {"id": "pw-sel-5", "question": "How do you handle dynamic selectors and shadow DOM?", "keywords": ["shadow", "pierce", "css=light", "dynamic", "wait", "attribute"], "model_answer": "Playwright pierces shadow DOM by default for CSS selectors. For dynamic elements, use text/role selectors that match visible content, combine with auto-waiting, or use attribute selectors. Use css:light= to opt out of shadow DOM piercing."},
    ],
    "pw-actions": [
        {"id": "pw-act-1", "question": "What are the common user actions available in Playwright?", "keywords": ["click", "fill", "type", "check", "select", "hover", "drag", "press"], "model_answer": "Playwright provides click(), dblclick(), fill() for inputs, type() for keystroke simulation, check()/uncheck() for checkboxes, selectOption() for dropdowns, hover(), dragTo(), press() for keyboard keys, and setInputFiles() for file uploads."},
        {"id": "pw-act-2", "question": "How does Playwright handle assertions and what types are available?", "keywords": ["expect", "toBeVisible", "toHaveText", "toHaveValue", "auto-retry", "timeout", "soft"], "model_answer": "Playwright uses expect() with auto-retrying assertions: toBeVisible(), toHaveText(), toHaveValue(), toBeChecked(), toHaveCount(), toHaveURL(), toContainText(). Assertions retry until timeout. Soft assertions (expect.soft) don't stop test execution on failure."},
        {"id": "pw-act-3", "question": "Explain the difference between fill() and type() in Playwright.", "keywords": ["fill", "clear", "value", "type", "keystroke", "event", "key"], "model_answer": "fill() clears the field and sets the value directly - it's faster and more reliable. type() simulates individual keystrokes with key events (keydown, keypress, keyup) - useful when testing autocomplete, input validation, or key event handlers."},
        {"id": "pw-act-4", "question": "How do you perform keyboard and mouse operations?", "keywords": ["keyboard", "press", "mouse", "click", "position", "modifier", "shortcut"], "model_answer": "Use page.keyboard.press('Enter'), page.keyboard.type('text'), page.keyboard.down/up() for modifiers. Mouse: page.mouse.click(x,y), page.mouse.move(), page.mouse.wheel(). Actions support modifier keys: click({modifiers: ['Shift']})."},
        {"id": "pw-act-5", "question": "What is the auto-waiting mechanism and how does it work?", "keywords": ["actionability", "visible", "enabled", "stable", "attached", "receives events"], "model_answer": "Before each action, Playwright waits for the element to be attached to DOM, visible, stable (not animating), enabled, and able to receive events. This happens automatically with configurable timeout, eliminating explicit wait commands."},
    ],
    "pw-advanced": [
        {"id": "pw-adv-1", "question": "How do you handle file uploads and downloads in Playwright?", "keywords": ["setInputFiles", "filechooser", "download", "waitForEvent", "saveAs", "path"], "model_answer": "Upload: use locator.setInputFiles('path') or listen for filechooser event for non-input uploads. Download: listen for download event with page.waitForEvent('download'), then saveAs() or get path(). Both support multiple files and programmatic blob creation."},
        {"id": "pw-adv-2", "question": "Explain how to handle multiple browser contexts and pages.", "keywords": ["context", "newPage", "popup", "tab", "waitForEvent", "page", "parallel"], "model_answer": "Create contexts with browser.newContext() for isolated sessions. Each context can have multiple pages via context.newPage(). Handle popups with page.waitForEvent('popup'). Use multiple contexts for testing multi-user scenarios or parallel isolated tests."},
        {"id": "pw-adv-3", "question": "How does network interception work in Playwright?", "keywords": ["route", "fulfill", "abort", "continue", "mock", "request", "response"], "model_answer": "Use page.route(url, handler) to intercept requests. Handler can route.fulfill() with custom response, route.abort() to block, or route.continue() to modify and forward. Useful for mocking APIs, testing error states, and controlling network behavior."},
        {"id": "pw-adv-4", "question": "How do you handle iframes in Playwright?", "keywords": ["frameLocator", "frame", "contentFrame", "locator", "nested", "cross-origin"], "model_answer": "Use page.frameLocator('#iframe') to get a locator scoped to the iframe's content. Chain with regular locators: page.frameLocator('#frame').locator('button'). For nested iframes, chain frameLocator calls. Supports cross-origin iframes automatically."},
        {"id": "pw-adv-5", "question": "What are Playwright's tracing capabilities?", "keywords": ["trace", "start", "stop", "viewer", "screenshot", "network", "console", "actions"], "model_answer": "Start tracing with context.tracing.start({screenshots: true, snapshots: true}). Stop with tracing.stop({path: 'trace.zip'}). View with npx playwright show-trace trace.zip. Captures screenshots, DOM snapshots, network requests, console logs, and action timeline."},
    ],
    "pw-pom": [
        {"id": "pw-pom-1", "question": "What is the Page Object Model pattern and why use it?", "keywords": ["encapsulate", "reusable", "maintainable", "separation", "selectors", "methods", "class"], "model_answer": "POM encapsulates page elements and interactions in classes. Each page/component gets a class with selectors as properties and actions as methods. Benefits: reusability, maintainability (update selectors in one place), separation of test logic from page structure, readability."},
        {"id": "pw-pom-2", "question": "How do Playwright fixtures support POM?", "keywords": ["fixture", "extend", "test.extend", "setup", "teardown", "dependency injection"], "model_answer": "Playwright test.extend() creates custom fixtures that inject page objects into tests. Fixtures handle setup/teardown automatically, support dependency chains, and provide clean test isolation. Tests declare needed page objects as fixture parameters."},
        {"id": "pw-pom-3", "question": "Describe best practices for structuring a POM framework.", "keywords": ["pages", "components", "base page", "fixtures", "helpers", "config", "structure"], "model_answer": "Structure: pages/ directory with one class per page, components/ for reusable UI components, BasePage class with common methods, fixtures/ for test setup, helpers/ for utilities, config for environment settings. Keep page methods focused on single actions."},
        {"id": "pw-pom-4", "question": "How do you handle component reuse across multiple pages?", "keywords": ["component", "composition", "header", "footer", "modal", "shared", "encapsulate"], "model_answer": "Create separate component classes (Header, Footer, Modal, Navigation) that can be composed into page objects. Pages instantiate components they contain. This avoids duplication and makes shared UI elements maintainable across page objects."},
        {"id": "pw-pom-5", "question": "How do you manage test data in a POM framework?", "keywords": ["data-driven", "factory", "fixture", "json", "csv", "environment", "dynamic"], "model_answer": "Use test data factories or builders for dynamic data, JSON/CSV files for static data sets, environment-specific configs, and fixtures for data setup/teardown. Keep test data separate from page objects. Use parameterized tests for data-driven scenarios."},
    ],
    "pw-api": [
        {"id": "pw-api-1", "question": "How do you perform API testing with Playwright?", "keywords": ["request", "APIRequestContext", "get", "post", "put", "delete", "json"], "model_answer": "Use Playwright's APIRequestContext via request fixture. Make HTTP calls: request.get(), post(), put(), delete(). Parse responses with response.json(). Supports headers, auth, form data, and file uploads. Can mix API and UI testing in same test."},
        {"id": "pw-api-2", "question": "How can you mock API responses in Playwright tests?", "keywords": ["route", "fulfill", "mock", "json", "status", "headers", "handler"], "model_answer": "Use page.route() to intercept API calls and route.fulfill() with mock data: page.route('**/api/data', route => route.fulfill({status: 200, body: JSON.stringify(mockData)})). Useful for testing UI with specific API states without backend dependency."},
        {"id": "pw-api-3", "question": "Explain how to set up authentication state for API tests.", "keywords": ["storageState", "cookie", "token", "header", "context", "global setup"], "model_answer": "Authenticate once in global setup, save state with context.storageState({path: 'auth.json'}). Reuse in tests via use: {storageState: 'auth.json'}. For API-only auth, set headers in APIRequestContext: request.newContext({extraHTTPHeaders: {'Authorization': 'Bearer token'}})."},
        {"id": "pw-api-4", "question": "How do you validate API response schemas?", "keywords": ["json", "schema", "structure", "type check", "assertion", "status code"], "model_answer": "Check status with expect(response).toBeOK(). Validate JSON structure: const data = await response.json(); then assert properties, types, and values. Use TypeScript interfaces for compile-time checks. Libraries like ajv can validate against JSON schema definitions."},
        {"id": "pw-api-5", "question": "How do you handle API request chaining and dependencies?", "keywords": ["response", "token", "chain", "create", "then use", "sequential"], "model_answer": "Chain API calls by extracting data from responses: const user = await (await request.post('/api/users', {data: userData})).json(); then use user.id in subsequent calls. Use fixtures to set up dependent data. Handle auth tokens across request chains."},
    ],
    "pw-ci": [
        {"id": "pw-ci-1", "question": "How do you run Playwright tests in CI/CD pipelines?", "keywords": ["docker", "github actions", "jenkins", "headless", "install", "dependencies"], "model_answer": "Use official Playwright Docker images or install browsers in CI. Run tests headless (default in CI). GitHub Actions: use playwright-github-action. Jenkins: install via npm/pip, install system deps. Set CI-specific config: retries, workers, reporter."},
        {"id": "pw-ci-2", "question": "What strategies exist for parallel test execution?", "keywords": ["workers", "shard", "fullyParallel", "project", "split", "parallel"], "model_answer": "Configure workers in playwright.config: workers: 4 or '50%'. Use fullyParallel: true for file-level parallelism. Shard across CI machines: --shard=1/3. Group tests by project for different browser/config combinations running in parallel."},
        {"id": "pw-ci-3", "question": "How do you handle test reporting in CI?", "keywords": ["reporter", "html", "json", "junit", "allure", "artifacts", "trends"], "model_answer": "Configure reporters: html (interactive), json (machine-readable), junit (CI integration), line (terminal). Publish HTML report as CI artifact. Use JUnit reporter for CI test result integration. Combine with Allure for trend tracking across builds."},
        {"id": "pw-ci-4", "question": "What is the recommended approach for managing test environments in CI?", "keywords": ["environment", "config", "base url", "variables", "staging", "production"], "model_answer": "Use environment variables for base URL, credentials, feature flags. Define projects in config for different environments. Use .env files per environment. CI sets variables per pipeline stage. Use global setup for environment-specific preparation."},
        {"id": "pw-ci-5", "question": "How do you debug test failures in CI?", "keywords": ["trace", "screenshot", "video", "retry", "artifacts", "logs", "on failure"], "model_answer": "Enable trace: 'on-first-retry', screenshot: 'only-on-failure', video: 'retain-on-failure'. Upload trace/screenshot artifacts in CI. Review with trace viewer. Use retries to distinguish flaky from real failures. Check console logs and network traces."},
    ],

    # ─── API Testing ───
    "api-fundamentals": [
        {"id": "api-fund-1", "question": "Explain the key HTTP methods and when to use each.", "keywords": ["GET", "POST", "PUT", "PATCH", "DELETE", "idempotent", "safe"], "model_answer": "GET retrieves resources (safe, idempotent). POST creates resources (not idempotent). PUT replaces entire resource (idempotent). PATCH partially updates (not always idempotent). DELETE removes resource (idempotent). Safe methods don't modify state. Idempotent methods produce same result on repeated calls."},
        {"id": "api-fund-2", "question": "What are HTTP status codes and their categories?", "keywords": ["200", "201", "400", "401", "403", "404", "500", "2xx", "4xx", "5xx"], "model_answer": "1xx: Informational. 2xx: Success (200 OK, 201 Created, 204 No Content). 3xx: Redirection (301, 302, 304). 4xx: Client errors (400 Bad Request, 401 Unauthorized, 403 Forbidden, 404 Not Found). 5xx: Server errors (500 Internal, 502 Bad Gateway, 503 Unavailable)."},
        {"id": "api-fund-3", "question": "What are HTTP headers and which are important for API testing?", "keywords": ["Content-Type", "Authorization", "Accept", "Cache-Control", "CORS", "custom"], "model_answer": "Headers provide metadata. Key headers: Content-Type (request/response format), Authorization (credentials), Accept (desired response format), Cache-Control (caching behavior), CORS headers (cross-origin), X-Request-ID (tracing). Custom headers often used for API versioning, rate limiting info."},
        {"id": "api-fund-4", "question": "Explain REST API design principles.", "keywords": ["resource", "stateless", "uniform interface", "URI", "representation", "HATEOAS"], "model_answer": "REST principles: resource-based URIs (/users/123), stateless requests (no server-side session), uniform interface (standard HTTP methods), multiple representations (JSON, XML), layered system architecture. Resources identified by URIs, manipulated through representations."},
        {"id": "api-fund-5", "question": "What is the difference between query parameters, path parameters, and request body?", "keywords": ["path", "query", "body", "filter", "identifier", "json", "payload"], "model_answer": "Path parameters identify specific resources: /users/{id}. Query parameters filter/sort collections: /users?role=admin&sort=name. Request body carries data for creation/updates (JSON/XML payload). Path = which resource, query = how to filter/modify response, body = data to send."},
    ],
    "api-tools": [
        {"id": "api-tools-1", "question": "Compare Postman and programmatic API testing approaches.", "keywords": ["Postman", "GUI", "collection", "automation", "code", "requests", "pytest"], "model_answer": "Postman offers GUI for manual exploration, collections for organizing requests, environments for variables, and Newman for CI. Programmatic testing (Python requests + pytest) offers version control, complex logic, CI integration, data-driven testing, and better maintainability for large suites."},
        {"id": "api-tools-2", "question": "How do you use Python's requests library for API testing?", "keywords": ["requests", "get", "post", "json", "headers", "session", "response"], "model_answer": "Import requests; use requests.get(url), .post(url, json=data), .put(), .delete(). Access response: r.status_code, r.json(), r.headers, r.text. Use Session() for persistent cookies/headers. Set timeouts, auth, and verify SSL certificates."},
        {"id": "api-tools-3", "question": "What are API testing best practices for test organization?", "keywords": ["arrange", "act", "assert", "fixture", "cleanup", "isolation", "data"], "model_answer": "Follow AAA pattern: Arrange (setup data), Act (make API call), Assert (verify response). Use fixtures for setup/teardown. Isolate tests (no shared state). Clean up created data. Use factories for test data. Group tests by endpoint/feature. Parameterize for data-driven tests."},
        {"id": "api-tools-4", "question": "How do you handle API authentication in test frameworks?", "keywords": ["token", "fixture", "session", "header", "login", "refresh", "reuse"], "model_answer": "Create auth fixture that logs in once and provides token. Store token in session fixture for reuse across tests. Set Authorization header automatically. Handle token refresh for long test suites. Use different auth levels for different test scenarios."},
        {"id": "api-tools-5", "question": "Explain API test reporting and documentation.", "keywords": ["allure", "html", "report", "swagger", "openapi", "documentation", "coverage"], "model_answer": "Use Allure or HTML reports for test results with request/response details. Track API coverage against OpenAPI/Swagger specs. Include request/response in failure reports. Generate API documentation from tests. Track metrics: pass rate, response times, coverage."},
    ],
    "api-auth": [
        {"id": "api-auth-1", "question": "Explain JWT authentication and its components.", "keywords": ["header", "payload", "signature", "base64", "claims", "expiry", "stateless"], "model_answer": "JWT has three parts: Header (algorithm, type), Payload (claims like sub, exp, iat), Signature (HMAC/RSA of header+payload). Base64url encoded, dot-separated. Stateless auth: server verifies signature without session storage. Contains expiry for security."},
        {"id": "api-auth-2", "question": "What is OAuth 2.0 and how does it work?", "keywords": ["authorization", "grant", "token", "scope", "client", "resource server", "flow"], "model_answer": "OAuth 2.0 is an authorization framework. Key flows: Authorization Code (web apps), Client Credentials (server-to-server), Implicit (SPAs, deprecated). Client requests authorization, receives access token with scopes, uses token to access resource server. Separates authentication from authorization."},
        {"id": "api-auth-3", "question": "How do you test API authentication security?", "keywords": ["expired", "invalid", "missing", "privilege", "injection", "brute force", "token"], "model_answer": "Test: expired tokens (should 401), invalid tokens (should 401), missing tokens (should 401), wrong privilege level (should 403), token in different case, SQL/NoSQL injection in auth fields, brute force protection, token refresh flow, concurrent sessions, logout invalidation."},
        {"id": "api-auth-4", "question": "What is the difference between authentication and authorization?", "keywords": ["identity", "permission", "who", "what", "401", "403", "role", "RBAC"], "model_answer": "Authentication verifies identity (who are you?), returns 401 on failure. Authorization checks permissions (what can you do?), returns 403 on failure. RBAC assigns roles with permissions. Authentication happens first, then authorization checks access rights."},
        {"id": "api-auth-5", "question": "How do you handle API keys vs Bearer tokens?", "keywords": ["API key", "bearer", "header", "query", "rotation", "scope", "security"], "model_answer": "API keys: simple, often in header/query, identify the application, limited scope control. Bearer tokens: standards-based, carry user context, support expiry and refresh, fine-grained scopes. API keys for server-to-server, bearer tokens for user-context APIs. Both need rotation policies."},
    ],
    "api-validation": [
        {"id": "api-val-1", "question": "How do you validate API response structure?", "keywords": ["schema", "json", "type", "required", "nested", "array", "format"], "model_answer": "Validate status code, content type, JSON structure (required fields, data types, nested objects, arrays). Use JSON Schema validation (ajv, jsonschema). Check field formats (dates, emails, UUIDs). Verify pagination structure. Assert null/empty handling."},
        {"id": "api-val-2", "question": "What is JSON Schema validation and why is it important?", "keywords": ["schema", "contract", "type", "required", "pattern", "validation", "drift"], "model_answer": "JSON Schema defines expected response structure: types, required fields, patterns, enums, nested schemas. Important for contract testing (catching API drift), automated validation, documentation generation. Catches breaking changes early in development."},
        {"id": "api-val-3", "question": "How do you test error responses and edge cases?", "keywords": ["boundary", "null", "empty", "large", "special characters", "error format"], "model_answer": "Test: empty strings, null values, missing required fields, boundary values (min/max), large payloads, special characters, SQL injection strings, unicode, very long strings. Verify consistent error response format with status code, error message, and error code."},
        {"id": "api-val-4", "question": "Explain data integrity testing for APIs.", "keywords": ["CRUD", "consistency", "create", "read", "verify", "database", "round-trip"], "model_answer": "Test full CRUD cycle: Create resource (POST) -> Read back (GET) -> Verify all fields match -> Update (PUT/PATCH) -> Read back -> Verify changes -> Delete -> Verify 404. Check database state matches API responses. Test concurrent modifications and conflict handling."},
        {"id": "api-val-5", "question": "How do you handle response time validation in API tests?", "keywords": ["SLA", "timeout", "performance", "threshold", "latency", "benchmark"], "model_answer": "Set response time thresholds per endpoint based on SLAs. Assert response time in tests: assert response.elapsed.total_seconds() < 2.0. Track trends over time. Set CI pipeline gates. Test under load for realistic numbers. Separate functional from performance assertions."},
    ],
    "api-automation": [
        {"id": "api-auto-1", "question": "How do you design an API test automation framework?", "keywords": ["structure", "config", "client", "assertions", "data", "reporting", "ci"], "model_answer": "Structure: api_client/ (HTTP wrappers), tests/ (organized by feature), data/ (test data, schemas), config/ (environments), conftest.py (fixtures). Use base client class with auth, logging, retry. Custom assertions for response validation. CI integration with reporting."},
        {"id": "api-auto-2", "question": "Explain data-driven API testing.", "keywords": ["parameterize", "csv", "json", "fixture", "test data", "multiple", "combinations"], "model_answer": "Use pytest parametrize to run same test with different data sets. Load test data from CSV/JSON files. Create data factories for dynamic data. Test boundary values, valid/invalid inputs, different user roles. Separate test logic from test data for maintainability."},
        {"id": "api-auto-3", "question": "How do you handle API test dependencies and ordering?", "keywords": ["fixture", "setup", "teardown", "independent", "cleanup", "state", "idempotent"], "model_answer": "Prefer independent tests (setup own data via fixtures). When order matters, use session-scoped fixtures for shared setup. Clean up with teardown/finalizers. Use factory functions for test data creation. Avoid test interdependencies. Make tests idempotent."},
        {"id": "api-auto-4", "question": "What is contract testing and how does it relate to API testing?", "keywords": ["consumer", "provider", "pact", "contract", "breaking change", "compatibility"], "model_answer": "Contract testing verifies API producer/consumer agreements without full integration. Consumer defines expected interactions (contract). Provider verifies it can fulfill contracts. Tools like Pact automate this. Catches breaking changes early, enables independent deployment."},
        {"id": "api-auto-5", "question": "How do you implement retry and error handling in API tests?", "keywords": ["retry", "backoff", "timeout", "transient", "flaky", "resilience", "circuit"], "model_answer": "Implement retry with exponential backoff for transient errors (5xx, timeouts). Set request timeouts. Distinguish transient from permanent failures. Use retry libraries (tenacity, urllib3.Retry). Log all attempts. Set max retries to prevent infinite loops. Handle rate limiting (429)."},
    ],
    "api-advanced": [
        {"id": "api-adv-1", "question": "How does GraphQL testing differ from REST API testing?", "keywords": ["query", "mutation", "schema", "introspection", "variables", "resolver", "over-fetching"], "model_answer": "GraphQL uses single endpoint with queries (read) and mutations (write). Test: query validation, variable handling, nested resolvers, error format, authorization per field, N+1 problems, query complexity limits. Schema introspection for coverage. No over/under-fetching but different error patterns."},
        {"id": "api-adv-2", "question": "Explain WebSocket testing challenges and approaches.", "keywords": ["connection", "message", "bidirectional", "event", "persistent", "protocol", "real-time"], "model_answer": "WebSocket testing challenges: bidirectional communication, persistent connections, event-driven messages, ordering, reconnection handling. Use websocket-client library. Test: connection lifecycle, message format, authentication, concurrent connections, error handling, load testing with many connections."},
        {"id": "api-adv-3", "question": "What is gRPC and how do you test gRPC services?", "keywords": ["protobuf", "service", "streaming", "contract", "typed", "performance", "grpcurl"], "model_answer": "gRPC uses Protocol Buffers for strongly-typed contracts. Supports unary, server/client/bidirectional streaming. Test with grpcurl (CLI), custom clients from proto files. Verify: serialization, streaming behavior, error codes, metadata, deadlines, load balancing. Proto files serve as contracts."},
        {"id": "api-adv-4", "question": "How do you implement contract testing for microservices?", "keywords": ["pact", "consumer", "provider", "broker", "verification", "deploy", "compatibility"], "model_answer": "Consumer writes expectations (Pact files). Provider verifies against contracts. Pact Broker stores and shares contracts. CI verifies on every build. 'Can I Deploy' check before release. Each service tests independently against contracts, enabling confident independent deployment."},
        {"id": "api-adv-5", "question": "Describe API versioning strategies and testing implications.", "keywords": ["version", "url", "header", "backward", "deprecation", "migration", "compatibility"], "model_answer": "Strategies: URL path (/v1/users), header (Accept-Version), query parameter. Testing: verify all supported versions work, test backward compatibility, test version negotiation, test deprecation warnings, test migration paths. Maintain test suites per active version."},
    ],

    # ─── Performance Testing ───
    "perf-intro": [
        {"id": "perf-intro-1", "question": "What are the different types of performance testing?", "keywords": ["load", "stress", "endurance", "spike", "volume", "scalability"], "model_answer": "Load testing: expected user load. Stress testing: beyond capacity to find breaking point. Endurance/soak: sustained load over time for memory leaks. Spike testing: sudden load increase. Volume testing: large data volumes. Scalability testing: how system scales with added resources."},
        {"id": "perf-intro-2", "question": "What are key performance metrics to monitor?", "keywords": ["response time", "throughput", "error rate", "concurrent", "latency", "percentile"], "model_answer": "Response time (avg, p50, p95, p99), throughput (requests/second), error rate (%), concurrent users, CPU/memory utilization, network bandwidth, database query time, connection pool usage. Focus on percentiles over averages for real user experience."},
        {"id": "perf-intro-3", "question": "How do you design a performance test plan?", "keywords": ["scenario", "workload", "baseline", "target", "ramp", "think time", "SLA"], "model_answer": "Define SLAs/targets. Identify critical user scenarios. Create workload model (user distribution, think times). Establish baseline. Design ramp-up strategy. Plan: load, stress, endurance tests. Set pass/fail criteria. Identify monitoring points. Plan for data and environment setup."},
        {"id": "perf-intro-4", "question": "What is the difference between performance testing environments and production?", "keywords": ["scale", "data", "infrastructure", "configuration", "network", "realistic"], "model_answer": "Differences: infrastructure scale (often smaller), data volume (synthetic vs real), network topology, third-party integrations (mocked), configuration tuning. Mitigate by: scaling results proportionally, using production-like data volumes, matching key configurations, testing with realistic network conditions."},
        {"id": "perf-intro-5", "question": "How do you identify performance bottlenecks?", "keywords": ["profiling", "monitoring", "database", "CPU", "memory", "network", "APM"], "model_answer": "Use APM tools (New Relic, Datadog) for end-to-end tracing. Profile: CPU (profilers), memory (heap dumps), database (slow query logs, explain plans), network (packet analysis). Monitor resource utilization during load tests. Correlate metrics with load patterns."},
    ],
    "perf-locust": [
        {"id": "perf-loc-1", "question": "How does Locust work and what are its key concepts?", "keywords": ["user", "task", "wait time", "host", "swarm", "Python", "distributed"], "model_answer": "Locust defines User classes with tasks (decorated methods simulating user behavior). Users have wait_time between tasks. Run against target host. Web UI shows real-time stats. Written in pure Python. Supports distributed testing across multiple machines via master/worker mode."},
        {"id": "perf-loc-2", "question": "How do you create realistic user scenarios in Locust?", "keywords": ["task", "weight", "sequence", "between", "HttpUser", "on_start", "think time"], "model_answer": "Use @task(weight) for frequency distribution. SequentialTaskSet for ordered flows. on_start() for user setup (login). between(min, max) for realistic think times. Multiple User classes for different personas. Use events for custom metrics. Chain tasks with shared state."},
        {"id": "perf-loc-3", "question": "Explain Locust's distributed testing mode.", "keywords": ["master", "worker", "distributed", "scale", "command", "report", "aggregate"], "model_answer": "Master coordinates workers, aggregates results, serves web UI. Workers generate load. Start master: locust --master. Start workers: locust --worker --master-host=IP. Workers can run on different machines. Master distributes users across workers. Results aggregated centrally."},
        {"id": "perf-loc-4", "question": "How do you handle authentication and session management in Locust?", "keywords": ["on_start", "login", "cookie", "token", "session", "client", "header"], "model_answer": "Use on_start() method to authenticate (login API call, store token). Locust's HttpUser maintains cookies automatically. Set custom headers: self.client.headers['Authorization'] = f'Bearer {token}'. Each user instance has its own session. Handle token refresh in tasks."},
        {"id": "perf-loc-5", "question": "How do you analyze and report Locust test results?", "keywords": ["statistics", "percentile", "csv", "web UI", "chart", "failure", "custom"], "model_answer": "Web UI shows real-time charts: RPS, response times, failures. Download CSV reports (stats, failures, exceptions). Use --csv flag for automatic export. Custom reporting via event hooks (request_success, request_failure). Integrate with Grafana/InfluxDB for historical tracking."},
    ],
    "perf-jmeter": [
        {"id": "perf-jm-1", "question": "What are the core components of a JMeter test plan?", "keywords": ["thread group", "sampler", "listener", "assertion", "timer", "config", "controller"], "model_answer": "Test Plan contains Thread Groups (virtual users). Samplers send requests (HTTP, JDBC, etc). Listeners collect results (graphs, tables). Assertions validate responses. Timers add delays. Config elements set defaults. Logic Controllers manage flow (loops, conditions). Pre/Post processors transform data."},
        {"id": "perf-jm-2", "question": "How do you parameterize JMeter tests?", "keywords": ["CSV", "variable", "user-defined", "function", "random", "counter", "data set"], "model_answer": "CSV Data Set Config reads test data from files. User Defined Variables for constants. Functions: __Random(), __time(), __counter(). Variable syntax: ${varName}. Each thread gets unique data row from CSV. Regular expression extractors capture dynamic values from responses."},
        {"id": "perf-jm-3", "question": "Explain correlation in JMeter.", "keywords": ["extract", "regex", "json", "xpath", "dynamic", "variable", "session"], "model_answer": "Correlation captures dynamic values from responses for subsequent requests. Use Regular Expression Extractor, JSON Extractor, or XPath Extractor. Common for session IDs, CSRF tokens, dynamic IDs. Extract from response body/headers, store in variables, reference in later requests."},
        {"id": "perf-jm-4", "question": "How do you run JMeter tests in non-GUI mode?", "keywords": ["command line", "non-gui", "jtl", "report", "distributed", "properties"], "model_answer": "Run: jmeter -n -t test.jmx -l results.jtl -e -o report/. -n for non-GUI (required for load tests). -t specifies test plan. -l saves results. -e -o generates HTML report. Pass properties: -Jthreads=100. Distributed: -R server1,server2. Non-GUI uses less resources than GUI mode."},
        {"id": "perf-jm-5", "question": "What are JMeter best practices for accurate results?", "keywords": ["non-gui", "listener", "ramp", "think time", "assertions", "resource", "realistic"], "model_answer": "Always run in non-GUI mode. Minimize listeners during test. Use ramp-up period. Add realistic think times. Use assertions sparingly (they add overhead). Run on dedicated machine. Monitor JMeter machine resources. Use distributed testing for high load. Warm up before measuring."},
    ],
    "perf-analysis": [
        {"id": "perf-an-1", "question": "How do you analyze response time distributions?", "keywords": ["percentile", "average", "median", "p95", "p99", "histogram", "outlier"], "model_answer": "Use percentiles over averages: p50 (median), p95, p99 show real user experience. Averages hide outliers. Plot histograms for distribution shape. Identify bimodal distributions (may indicate two code paths). Track percentiles over time for trend analysis. Set SLAs on p95/p99."},
        {"id": "perf-an-2", "question": "What are common performance bottlenecks?", "keywords": ["database", "CPU", "memory", "network", "lock", "connection pool", "GC"], "model_answer": "Common bottlenecks: slow database queries (missing indexes, N+1), CPU saturation (inefficient algorithms), memory leaks (GC pressure), network latency, connection pool exhaustion, lock contention, thread starvation, disk I/O. Each has specific symptoms and diagnostic approaches."},
        {"id": "perf-an-3", "question": "How do you establish performance baselines?", "keywords": ["baseline", "benchmark", "consistent", "environment", "compare", "regression", "trend"], "model_answer": "Run standardized tests on consistent environment. Record key metrics: response times, throughput, resource usage. Test at multiple load levels. Document environment config. Store results for comparison. Run baselines after each release to detect regressions. Use consistent data volumes."},
        {"id": "perf-an-4", "question": "Explain the concept of throughput vs latency.", "keywords": ["throughput", "latency", "RPS", "response time", "capacity", "queue", "saturation"], "model_answer": "Throughput: requests processed per second (system capacity). Latency: time for individual request completion (user experience). They're related but different: high throughput can coexist with high latency (queuing). As load approaches saturation, latency increases while throughput plateaus or decreases."},
        {"id": "perf-an-5", "question": "How do you create meaningful performance test reports?", "keywords": ["executive", "technical", "trend", "SLA", "recommendation", "comparison", "visual"], "model_answer": "Include: executive summary (pass/fail vs SLAs), test configuration (load profile, environment), key metrics (response times, throughput, errors), resource utilization graphs, comparison with baseline, bottleneck analysis, recommendations. Use visualizations. Separate executive and technical sections."},
    ],
    "perf-ci": [
        {"id": "perf-ci-1", "question": "How do you integrate performance tests into CI/CD pipelines?", "keywords": ["gate", "threshold", "automated", "pipeline", "fail", "baseline", "report"], "model_answer": "Run lightweight performance tests as pipeline gate. Set pass/fail thresholds (response time, error rate). Compare against baseline. Fail build on regression. Store results for trends. Use dedicated performance test environment. Schedule heavy tests nightly, light tests on every build."},
        {"id": "perf-ci-2", "question": "What are performance test gates and how do you define them?", "keywords": ["threshold", "SLA", "p95", "error rate", "fail", "automated", "criteria"], "model_answer": "Gates are automated pass/fail criteria: p95 response time < 2s, error rate < 1%, throughput > 100 RPS. Define per endpoint or overall. Compare against previous build or fixed baseline. Strict gates for critical paths, advisory gates for non-critical. Include resource utilization thresholds."},
        {"id": "perf-ci-3", "question": "How do you track performance trends across builds?", "keywords": ["trend", "graph", "history", "regression", "dashboard", "metrics", "time series"], "model_answer": "Store test results in time-series database (InfluxDB, Prometheus). Visualize with Grafana dashboards. Track key metrics per build: p95, throughput, errors. Set alerts for trend changes. Compare release branches. Identify gradual degradation before it hits thresholds."},
        {"id": "perf-ci-4", "question": "What is shift-left performance testing?", "keywords": ["early", "developer", "unit", "component", "benchmark", "micro", "continuous"], "model_answer": "Test performance early in development, not just before release. Developer-level benchmarks for critical code paths. Component-level performance tests in CI. API response time assertions in integration tests. Catch regressions when they're introduced, not weeks later."},
        {"id": "perf-ci-5", "question": "How do you handle test environment consistency for performance testing?", "keywords": ["container", "infrastructure", "reproducible", "isolation", "data", "configuration"], "model_answer": "Use containerized environments (Docker/K8s) for consistency. Infrastructure as code for reproducible setup. Isolate from other workloads. Use consistent data volumes (snapshot/restore). Match production configuration ratios. Monitor environment health during tests. Document and version environment specs."},
    ],

    # ─── Security Testing ───
    "sec-intro": [
        {"id": "sec-intro-1", "question": "What is the OWASP Top 10 and why is it important for security testing?", "keywords": ["OWASP", "top 10", "vulnerabilities", "web", "standard", "risk", "injection", "broken auth"], "model_answer": "OWASP Top 10 is a standard awareness document listing the most critical web application security risks. Updated periodically, it includes: Broken Access Control, Cryptographic Failures, Injection, Insecure Design, Security Misconfiguration, Vulnerable Components, Authentication Failures, Data Integrity Failures, Logging Failures, and SSRF. It guides security testing priorities and compliance requirements."},
        {"id": "sec-intro-2", "question": "Explain the difference between SAST, DAST, and IAST.", "keywords": ["static", "dynamic", "interactive", "source code", "runtime", "white box", "black box", "pipeline"], "model_answer": "SAST (Static Application Security Testing) analyzes source code without running it - white box, finds issues early but has false positives. DAST (Dynamic Application Security Testing) tests running applications from outside - black box, finds runtime issues but can't see code. IAST (Interactive) combines both by instrumenting the application during testing, providing accurate results with code-level detail."},
        {"id": "sec-intro-3", "question": "What is threat modeling and how do you perform it?", "keywords": ["threat", "model", "STRIDE", "attack surface", "assets", "data flow", "mitigations", "risk"], "model_answer": "Threat modeling identifies potential security threats to a system. Process: 1) Define scope and assets, 2) Create architecture/data flow diagrams, 3) Identify threats using frameworks like STRIDE (Spoofing, Tampering, Repudiation, Information Disclosure, Denial of Service, Elevation of Privilege), 4) Rate risks (DREAD), 5) Define mitigations. Done early in design phase."},
        {"id": "sec-intro-4", "question": "What is the CIA triad in information security?", "keywords": ["confidentiality", "integrity", "availability", "security", "principles", "encryption", "access control"], "model_answer": "CIA triad is the foundational security model: Confidentiality ensures data is accessible only to authorized users (encryption, access controls). Integrity ensures data hasn't been tampered with (checksums, digital signatures). Availability ensures systems are accessible when needed (redundancy, DDoS protection). All security measures should address at least one of these principles."},
        {"id": "sec-intro-5", "question": "How do you create a security testing plan for a web application?", "keywords": ["scope", "reconnaissance", "vulnerability", "penetration", "tools", "reporting", "remediation", "risk"], "model_answer": "Security test plan: 1) Define scope and objectives, 2) Reconnaissance - gather info about the application, 3) Threat modeling - identify attack vectors, 4) Vulnerability scanning with automated tools (ZAP, Burp), 5) Manual penetration testing of critical flows, 6) API security testing, 7) Authentication/authorization testing, 8) Report findings with severity ratings and remediation recommendations."},
    ],
    "sec-web": [
        {"id": "sec-web-1", "question": "Explain Cross-Site Scripting (XSS) and its types.", "keywords": ["XSS", "reflected", "stored", "DOM", "script", "injection", "sanitize", "encode"], "model_answer": "XSS injects malicious scripts into web pages viewed by others. Types: Reflected XSS - payload in URL/request, reflected back immediately. Stored XSS - payload saved in database, displayed to all users (most dangerous). DOM-based XSS - client-side JavaScript processes untrusted data. Prevention: output encoding, Content Security Policy headers, input validation, sanitization libraries."},
        {"id": "sec-web-2", "question": "What is SQL injection and how do you prevent it?", "keywords": ["SQL", "injection", "parameterized", "prepared", "ORM", "input", "sanitize", "escape"], "model_answer": "SQL injection inserts malicious SQL through user input to manipulate database queries. Example: ' OR 1=1 -- in login form. Prevention: parameterized queries/prepared statements (never concatenate user input into SQL), ORM frameworks, input validation, least privilege database accounts, WAF rules. Test with tools like sqlmap."},
        {"id": "sec-web-3", "question": "Explain CSRF attacks and prevention mechanisms.", "keywords": ["CSRF", "token", "cross-site", "request forgery", "SameSite", "cookie", "origin", "referer"], "model_answer": "CSRF tricks authenticated users into submitting malicious requests. Attacker creates a page that makes requests to target site using victim's cookies. Prevention: CSRF tokens (unique per session/request), SameSite cookie attribute, checking Origin/Referer headers, requiring re-authentication for sensitive actions, using custom request headers (not sent by forms)."},
        {"id": "sec-web-4", "question": "What is Server-Side Request Forgery (SSRF)?", "keywords": ["SSRF", "server", "internal", "request", "metadata", "cloud", "whitelist", "URL"], "model_answer": "SSRF tricks the server into making requests to unintended locations, accessing internal resources. Attackers can reach internal services, cloud metadata endpoints (169.254.169.254), or port scan internal networks. Prevention: whitelist allowed URLs/domains, block private IP ranges, don't expose raw URLs to users, use URL parsers to validate, disable unnecessary URL schemes."},
        {"id": "sec-web-5", "question": "How do you test for broken authentication vulnerabilities?", "keywords": ["authentication", "brute force", "session", "password", "MFA", "credential stuffing", "lockout", "token"], "model_answer": "Test: brute force resistance (account lockout after N failures), credential stuffing with known breached passwords, session management (session fixation, timeout, invalidation on logout), password policy enforcement, MFA bypass attempts, token predictability, remember-me functionality, password reset flow security, default credentials, authentication bypass via direct URL access."},
    ],
    "sec-api": [
        {"id": "sec-api-1", "question": "What are the OWASP API Security Top 10 risks?", "keywords": ["BOLA", "broken", "authentication", "excessive data", "rate limiting", "BFLA", "mass assignment", "injection"], "model_answer": "OWASP API Security Top 10: 1) BOLA (Broken Object Level Authorization), 2) Broken Authentication, 3) Broken Object Property Level Authorization, 4) Unrestricted Resource Consumption, 5) Broken Function Level Authorization (BFLA), 6) Unrestricted Access to Sensitive Business Flows, 7) Server-Side Request Forgery, 8) Security Misconfiguration, 9) Improper Inventory Management, 10) Unsafe Consumption of APIs."},
        {"id": "sec-api-2", "question": "How do you test for Broken Object Level Authorization (BOLA)?", "keywords": ["BOLA", "IDOR", "authorization", "object", "ID", "access control", "horizontal", "privilege"], "model_answer": "BOLA (also called IDOR) occurs when users can access objects belonging to others by manipulating IDs. Test: authenticate as User A, note resource IDs, try accessing User B's resources by changing IDs in URLs/parameters. Test with sequential IDs, UUIDs, encoded values. Automate by replacing object references in requests. Check all CRUD operations. Verify server-side authorization checks exist per request."},
        {"id": "sec-api-3", "question": "Explain mass assignment vulnerabilities in APIs.", "keywords": ["mass assignment", "parameter", "binding", "whitelist", "DTO", "role", "admin", "overpost"], "model_answer": "Mass assignment occurs when APIs bind client-provided data directly to internal objects without filtering. Attacker adds extra fields (e.g., role=admin, is_verified=true) to requests. Prevention: use explicit whitelists of allowed fields (DTOs/serializers), never bind request data directly to database models, validate and filter all input fields, use separate read/write models."},
        {"id": "sec-api-4", "question": "How do you test API rate limiting and resource consumption?", "keywords": ["rate limit", "throttle", "DoS", "resource", "pagination", "timeout", "429", "quota"], "model_answer": "Test: send rapid requests to check if rate limiting exists (expect 429 status). Test with different API keys/IPs. Check: pagination limits (request page_size=999999), request body size limits, file upload size limits, query complexity limits (GraphQL), long-running request timeouts, concurrent connection limits. Verify rate limit headers (X-RateLimit-Remaining). Test if limits reset correctly."},
        {"id": "sec-api-5", "question": "What security headers should APIs implement?", "keywords": ["CORS", "Content-Type", "HSTS", "X-Content-Type", "CSP", "X-Frame", "cache", "headers"], "model_answer": "Essential API security headers: CORS (Access-Control-Allow-Origin - restrict to known domains), Content-Type (enforce application/json), X-Content-Type-Options: nosniff, Strict-Transport-Security (HSTS), Cache-Control: no-store for sensitive data, X-Request-ID for tracing, rate limit headers. Remove: Server, X-Powered-By, stack trace in errors. For web-facing APIs: CSP, X-Frame-Options."},
    ],
    "sec-tools": [
        {"id": "sec-tools-1", "question": "How do you use OWASP ZAP for security testing?", "keywords": ["ZAP", "proxy", "spider", "scan", "active", "passive", "intercept", "automated"], "model_answer": "OWASP ZAP is a free security testing tool. Usage: 1) Configure browser to proxy through ZAP, 2) Spider/crawl the application to discover URLs, 3) Run passive scan (analyzes traffic without modification), 4) Run active scan (sends attack payloads to find vulnerabilities), 5) Review alerts by risk level. Also supports: API scanning (import OpenAPI specs), authenticated scanning, CI/CD integration via CLI/API, custom scan policies."},
        {"id": "sec-tools-2", "question": "Compare Burp Suite and OWASP ZAP for penetration testing.", "keywords": ["Burp", "ZAP", "proxy", "scanner", "commercial", "free", "repeater", "intruder", "extensions"], "model_answer": "Burp Suite: commercial (Community free version limited), industry standard, excellent Repeater/Intruder tools, Burp Collaborator for out-of-band testing, extensive extension marketplace, better manual testing workflow. ZAP: fully free/open-source, good automated scanning, HUD for interactive testing, API for CI/CD, community scripts. Both: proxy-based, intercept/modify requests, spider/crawler, active/passive scanning. Choose Burp for manual pentesting, ZAP for automated CI/CD scanning."},
        {"id": "sec-tools-3", "question": "What are static analysis security testing (SAST) tools and how do they work?", "keywords": ["SAST", "static", "source code", "SonarQube", "Semgrep", "CodeQL", "false positive", "pipeline"], "model_answer": "SAST tools analyze source code for security vulnerabilities without executing it. Tools: SonarQube (multi-language, quality + security), Semgrep (pattern-based, fast, custom rules), CodeQL (GitHub, semantic analysis), Bandit (Python-specific), ESLint security plugins (JavaScript). They find: injection flaws, hardcoded secrets, insecure crypto, vulnerable dependencies. Integrate into CI/CD pipeline. Challenge: false positives require manual triage."},
        {"id": "sec-tools-4", "question": "How do you scan for vulnerable dependencies?", "keywords": ["dependency", "SCA", "CVE", "npm audit", "pip", "Snyk", "Dependabot", "vulnerability"], "model_answer": "Software Composition Analysis (SCA) tools: npm audit / yarn audit (JavaScript), pip-audit / safety (Python), Snyk (multi-language, CI/CD integration), Dependabot (GitHub native, auto-PRs), OWASP Dependency-Check (Java/.NET). They check dependencies against CVE databases (NVD). Best practices: run in CI/CD pipeline, block builds on critical CVEs, auto-update with Dependabot/Renovate, monitor continuously, maintain SBOM."},
        {"id": "sec-tools-5", "question": "How do you integrate security testing into CI/CD pipelines?", "keywords": ["CI/CD", "pipeline", "shift left", "gate", "SAST", "DAST", "SCA", "automated", "DevSecOps"], "model_answer": "DevSecOps pipeline integration: 1) Pre-commit: secret scanning (git-secrets, detect-secrets), 2) Build: SAST scan (SonarQube, Semgrep), dependency check (Snyk, npm audit), 3) Test: DAST scan (ZAP baseline), API security tests, 4) Deploy gate: fail on critical/high findings, 5) Production: continuous monitoring, WAF. Key: automate everything, set severity thresholds, minimize false positives, provide developer-friendly remediation guidance."},
    ],

    # ─── DevOps ───
    "devops-intro": [
        {"id": "devops-intro-1", "question": "What is DevOps and what problems does it solve?", "keywords": ["culture", "collaboration", "automation", "continuous", "delivery", "feedback", "silos", "agile"], "model_answer": "DevOps is a culture and set of practices that unifies software development (Dev) and IT operations (Ops). It solves: slow release cycles, dev/ops silos, manual error-prone deployments, lack of feedback loops, inconsistent environments. Key principles: automation, continuous integration/delivery, infrastructure as code, monitoring, collaboration, shared responsibility. Goal: deliver software faster, more reliably, with continuous improvement."},
        {"id": "devops-intro-2", "question": "Explain the difference between CI, CD (Continuous Delivery), and CD (Continuous Deployment).", "keywords": ["continuous integration", "delivery", "deployment", "automated", "pipeline", "manual approval", "production", "build"], "model_answer": "CI (Continuous Integration): developers merge code frequently, automated build and test on every commit. CD (Continuous Delivery): extends CI with automated release process, code is always deployable but requires manual approval to production. CD (Continuous Deployment): extends delivery with fully automated production deployment - every passing change goes live automatically. CI is prerequisite for both CDs."},
        {"id": "devops-intro-3", "question": "What are the key DevOps practices and tools categories?", "keywords": ["version control", "CI/CD", "IaC", "monitoring", "containerization", "configuration", "testing", "collaboration"], "model_answer": "Key practices and tools: Version Control (Git, GitHub/GitLab), CI/CD (Jenkins, GitHub Actions, GitLab CI), Containerization (Docker, Kubernetes), IaC (Terraform, Ansible, CloudFormation), Configuration Management (Ansible, Chef, Puppet), Monitoring (Prometheus, Grafana, Datadog), Logging (ELK Stack, Splunk), Artifact Management (Nexus, Artifactory), Collaboration (Slack, Jira), Security (Snyk, SonarQube)."},
        {"id": "devops-intro-4", "question": "What is the DevOps lifecycle and its stages?", "keywords": ["plan", "code", "build", "test", "release", "deploy", "operate", "monitor", "feedback"], "model_answer": "DevOps lifecycle (infinity loop): Plan (requirements, backlog), Code (development, version control), Build (compile, package), Test (automated testing, quality gates), Release (release management, approval), Deploy (automated deployment, IaC), Operate (infrastructure management, scaling), Monitor (logging, metrics, alerting). Continuous feedback flows back from Monitor to Plan, creating a continuous improvement cycle."},
        {"id": "devops-intro-5", "question": "How do you measure DevOps success with DORA metrics?", "keywords": ["DORA", "deployment frequency", "lead time", "MTTR", "change failure rate", "metrics", "performance"], "model_answer": "DORA (DevOps Research and Assessment) metrics: 1) Deployment Frequency - how often code deploys to production (elite: multiple per day), 2) Lead Time for Changes - time from commit to production (elite: <1 hour), 3) Mean Time to Recovery (MTTR) - time to restore service after failure (elite: <1 hour), 4) Change Failure Rate - percentage of deployments causing failures (elite: 0-15%). These four metrics correlate with organizational performance."},
    ],
    "devops-docker": [
        {"id": "devops-docker-1", "question": "What is Docker and how does containerization differ from virtualization?", "keywords": ["container", "image", "lightweight", "kernel", "VM", "isolation", "portable", "layer"], "model_answer": "Docker packages applications with their dependencies into containers. Unlike VMs which run full OS on hypervisor, containers share the host kernel, making them lightweight (MB vs GB), fast to start (seconds vs minutes), and more efficient. Containers provide process isolation via namespaces and cgroups. Docker uses layered images for efficient storage. Containers are portable across environments."},
        {"id": "devops-docker-2", "question": "Explain the Dockerfile and its key instructions.", "keywords": ["FROM", "RUN", "COPY", "CMD", "ENTRYPOINT", "EXPOSE", "ENV", "WORKDIR", "layer"], "model_answer": "Dockerfile defines how to build an image. Key instructions: FROM (base image), WORKDIR (set working directory), COPY/ADD (copy files into image), RUN (execute commands during build, creates layers), ENV (set environment variables), EXPOSE (document ports), CMD (default command, overridable), ENTRYPOINT (fixed command). Best practices: use specific base image tags, minimize layers, use multi-stage builds, order instructions for cache optimization."},
        {"id": "devops-docker-3", "question": "How does Docker Compose work and when do you use it?", "keywords": ["compose", "multi-container", "yaml", "services", "networks", "volumes", "depends_on", "orchestration"], "model_answer": "Docker Compose defines multi-container applications in a YAML file. Use it for: local development environments, testing with dependencies (database, cache, message queue). Key concepts: services (containers), networks (inter-container communication), volumes (persistent data), depends_on (startup order). Commands: docker-compose up -d, down, logs, exec. Ideal for development; use Kubernetes for production orchestration."},
        {"id": "devops-docker-4", "question": "What are Docker networking modes and how do containers communicate?", "keywords": ["bridge", "host", "overlay", "network", "DNS", "port", "mapping", "container communication"], "model_answer": "Docker networks: Bridge (default, containers on same bridge communicate via container name DNS), Host (container shares host network stack, no isolation), Overlay (multi-host networking for Swarm/K8s), None (no networking). Containers communicate via: service name DNS on custom bridge networks, exposed ports on host, shared networks. Port mapping (-p 8080:80) exposes container ports to host."},
        {"id": "devops-docker-5", "question": "What are Docker best practices for production?", "keywords": ["multi-stage", "non-root", "slim", "cache", ".dockerignore", "health check", "security", "scan"], "model_answer": "Production best practices: use multi-stage builds (smaller images), run as non-root user, use slim/alpine base images, leverage build cache (order instructions correctly), use .dockerignore, add HEALTHCHECK instructions, pin dependency versions, scan images for vulnerabilities (Trivy, Snyk), don't store secrets in images, use read-only filesystem where possible, limit container resources (CPU/memory)."},
    ],
    "devops-k8s": [
        {"id": "devops-k8s-1", "question": "What is Kubernetes and what problems does it solve?", "keywords": ["orchestration", "container", "scaling", "self-healing", "service discovery", "load balancing", "rollout", "cluster"], "model_answer": "Kubernetes (K8s) is a container orchestration platform that automates deployment, scaling, and management of containerized applications. It solves: manual container management at scale, service discovery and load balancing, automated rollouts/rollbacks, self-healing (restart failed containers), secret and configuration management, storage orchestration, horizontal auto-scaling."},
        {"id": "devops-k8s-2", "question": "Explain the key Kubernetes objects: Pod, Deployment, Service.", "keywords": ["pod", "deployment", "service", "replica", "selector", "ClusterIP", "NodePort", "LoadBalancer"], "model_answer": "Pod: smallest deployable unit, one or more containers sharing network/storage. Deployment: manages ReplicaSets, handles rolling updates, scaling, and rollbacks of Pods. Defines desired state (replicas, image version). Service: stable network endpoint for accessing Pods. Types: ClusterIP (internal), NodePort (external via node port), LoadBalancer (cloud provider LB), ExternalName (DNS alias)."},
        {"id": "devops-k8s-3", "question": "How do ConfigMaps and Secrets work in Kubernetes?", "keywords": ["ConfigMap", "Secret", "environment", "volume", "mount", "base64", "configuration", "decouple"], "model_answer": "ConfigMaps store non-sensitive configuration as key-value pairs. Secrets store sensitive data (passwords, tokens) base64-encoded (not encrypted by default). Both can be consumed as: environment variables, command-line arguments, or volume-mounted files. They decouple configuration from container images, enabling the same image across environments. Best practice: use external secret managers (Vault, AWS Secrets Manager) for production secrets."},
        {"id": "devops-k8s-4", "question": "What is an Ingress in Kubernetes?", "keywords": ["ingress", "controller", "routing", "host", "path", "TLS", "nginx", "load balancer"], "model_answer": "Ingress manages external HTTP/HTTPS access to services in a cluster. It provides: URL-based routing (path/host rules), TLS termination, name-based virtual hosting, load balancing. Requires an Ingress Controller (nginx-ingress, traefik, ALB controller). Ingress resource defines rules mapping hostnames/paths to backend services. More efficient than NodePort/LoadBalancer per service - single entry point for multiple services."},
        {"id": "devops-k8s-5", "question": "How do you perform rolling updates and rollbacks in Kubernetes?", "keywords": ["rolling update", "rollback", "strategy", "maxSurge", "maxUnavailable", "revision", "undo", "zero downtime"], "model_answer": "Rolling updates: Deployment gradually replaces old pods with new ones. Configure via strategy: maxSurge (extra pods during update), maxUnavailable (pods that can be down). Update: change image tag in deployment spec or kubectl set image. Monitor: kubectl rollout status. Rollback: kubectl rollout undo deployment/name (reverts to previous revision) or kubectl rollout undo --to-revision=N. Kubernetes maintains revision history for rollbacks."},
    ],
    "devops-cicd": [
        {"id": "devops-cicd-1", "question": "How do you design a CI/CD pipeline?", "keywords": ["stages", "build", "test", "deploy", "artifact", "gate", "environment", "automated"], "model_answer": "Pipeline stages: 1) Source (trigger on commit/PR), 2) Build (compile, create artifacts), 3) Unit Tests (fast, isolated), 4) Static Analysis (linting, SAST), 5) Integration Tests (with dependencies), 6) Artifact Storage (Docker registry, artifact repo), 7) Deploy to Staging (automated), 8) E2E/Smoke Tests, 9) Manual Approval Gate, 10) Deploy to Production, 11) Post-deploy verification. Design principles: fail fast, parallelize where possible, immutable artifacts."},
        {"id": "devops-cicd-2", "question": "Compare Jenkins, GitHub Actions, and GitLab CI.", "keywords": ["Jenkins", "GitHub Actions", "GitLab CI", "pipeline", "yaml", "self-hosted", "cloud", "marketplace"], "model_answer": "Jenkins: self-hosted, most flexible, huge plugin ecosystem, Groovy Jenkinsfile, requires infrastructure management. GitHub Actions: cloud-native, YAML workflows, tight GitHub integration, marketplace for actions, free for public repos. GitLab CI: built into GitLab, YAML .gitlab-ci.yml, integrated with GitLab features (registry, security), Auto DevOps. Choose Jenkins for complex enterprise needs, GitHub Actions for GitHub-hosted projects, GitLab CI for GitLab-based workflows."},
        {"id": "devops-cicd-3", "question": "What are GitHub Actions workflows and how do you create one?", "keywords": ["workflow", "yaml", "trigger", "job", "step", "action", "runner", "artifact", "secret"], "model_answer": "GitHub Actions uses YAML workflows in .github/workflows/. Key concepts: triggers (on: push, pull_request, schedule), jobs (run on runners, parallel by default), steps (individual tasks), actions (reusable units from marketplace). Use secrets for sensitive data, artifacts to pass data between jobs, matrix strategy for multi-version testing. Runners: GitHub-hosted (Ubuntu, Windows, macOS) or self-hosted."},
        {"id": "devops-cicd-4", "question": "How do you handle secrets and environment variables in CI/CD?", "keywords": ["secrets", "vault", "environment", "encrypted", "rotation", "least privilege", "injection", "manager"], "model_answer": "Best practices: never hardcode secrets in code/config, use platform secret management (GitHub Secrets, GitLab CI Variables, Jenkins Credentials), integrate with external vaults (HashiCorp Vault, AWS Secrets Manager), limit secret scope (per environment/job), rotate regularly, use least privilege, audit access, mask in logs. Inject as environment variables at runtime, never in build artifacts."},
        {"id": "devops-cicd-5", "question": "What are deployment strategies (blue-green, canary, rolling)?", "keywords": ["blue-green", "canary", "rolling", "zero downtime", "rollback", "traffic", "percentage", "strategy"], "model_answer": "Rolling: gradually replace old instances with new (Kubernetes default). Blue-Green: run two identical environments, switch traffic to new (green) after verification, instant rollback to blue. Canary: route small percentage of traffic to new version, gradually increase if metrics are good. Feature Flags: deploy code but control activation. Choose based on: risk tolerance, rollback speed needed, infrastructure cost, traffic splitting capability."},
    ],
    "devops-iac": [
        {"id": "devops-iac-1", "question": "What is Infrastructure as Code and why is it important?", "keywords": ["IaC", "declarative", "version control", "reproducible", "automated", "drift", "idempotent", "state"], "model_answer": "IaC manages infrastructure through code/config files instead of manual processes. Benefits: version controlled (track changes, review, rollback), reproducible (identical environments every time), automated (no manual steps), self-documenting, testable, prevents drift. Approaches: declarative (desired state - Terraform, CloudFormation) vs imperative (step-by-step - scripts, Ansible). Enables: disaster recovery, multi-environment consistency, scalability."},
        {"id": "devops-iac-2", "question": "Explain Terraform basics: providers, resources, state.", "keywords": ["Terraform", "provider", "resource", "state", "plan", "apply", "HCL", "module"], "model_answer": "Terraform uses HCL to define infrastructure. Providers: plugins for cloud platforms (AWS, Azure, GCP). Resources: infrastructure components (instances, networks, databases). State: tracks real-world resources mapping to config (stored in terraform.tfstate). Workflow: terraform init (install providers), plan (preview changes), apply (create/update resources), destroy (tear down). Modules: reusable resource groups. State should be stored remotely (S3, Terraform Cloud) for team use."},
        {"id": "devops-iac-3", "question": "How does Ansible work and what are playbooks?", "keywords": ["Ansible", "agentless", "SSH", "playbook", "task", "role", "inventory", "idempotent", "YAML"], "model_answer": "Ansible is agentless configuration management tool using SSH. Inventory: list of target hosts. Playbooks: YAML files defining automation tasks. Tasks use modules (apt, copy, service, template). Roles organize tasks into reusable units. Key features: idempotent (safe to run repeatedly), push-based, no agent installation needed, Jinja2 templating, variables and facts. Use for: configuration management, application deployment, orchestration."},
        {"id": "devops-iac-4", "question": "What is Terraform state and how do you manage it?", "keywords": ["state", "remote", "backend", "lock", "workspace", "import", "drift", "refresh"], "model_answer": "Terraform state maps config to real resources. Management: use remote backends (S3+DynamoDB, Terraform Cloud) for team collaboration, enable state locking to prevent concurrent modifications, use workspaces for environment separation, never edit state manually. Commands: terraform state list/show/mv/rm, terraform import (bring existing resources under management), terraform refresh (sync state with reality). Protect state file - it may contain sensitive data."},
        {"id": "devops-iac-5", "question": "Compare Terraform, Ansible, and CloudFormation.", "keywords": ["Terraform", "Ansible", "CloudFormation", "multi-cloud", "configuration", "provisioning", "declarative", "AWS"], "model_answer": "Terraform: multi-cloud provisioning, declarative HCL, state management, strong module ecosystem. Ansible: configuration management + provisioning, agentless, YAML playbooks, procedural, good for config management. CloudFormation: AWS-only, native integration, no state file management needed, JSON/YAML templates. Use Terraform for multi-cloud infrastructure, Ansible for server configuration/deployment, CloudFormation for AWS-only shops wanting native tooling. Terraform + Ansible is a common combo."},
    ],
    "devops-monitoring": [
        {"id": "devops-mon-1", "question": "What is observability and how does it differ from monitoring?", "keywords": ["observability", "monitoring", "metrics", "logs", "traces", "pillars", "unknown unknowns", "debug"], "model_answer": "Monitoring tracks predefined metrics and alerts on known failure modes (known unknowns). Observability is the ability to understand system state from external outputs - you can debug novel issues (unknown unknowns). Three pillars: Metrics (quantitative measurements over time), Logs (discrete events with context), Traces (request journey across services). Observability enables asking new questions without deploying new code."},
        {"id": "devops-mon-2", "question": "How does Prometheus work for metrics collection?", "keywords": ["Prometheus", "pull", "scrape", "PromQL", "time series", "exporter", "alert", "target"], "model_answer": "Prometheus is a pull-based metrics system. It scrapes HTTP endpoints (/metrics) at configured intervals. Components: Prometheus server (scrapes, stores time-series data), exporters (expose metrics from services), AlertManager (handles alerts), PromQL (query language). Data model: metric name + labels + timestamp + value. Types: counter (monotonic), gauge (up/down), histogram (distribution), summary. Pull model simplifies service configuration."},
        {"id": "devops-mon-3", "question": "What is Grafana and how do you create effective dashboards?", "keywords": ["Grafana", "dashboard", "panel", "data source", "visualization", "alert", "template", "variable"], "model_answer": "Grafana visualizes metrics from multiple data sources (Prometheus, InfluxDB, Elasticsearch). Dashboard design: use variables for dynamic filtering, organize panels by service/layer, include RED metrics (Rate, Errors, Duration), set appropriate time ranges, add annotations for deployments. Best practices: golden signals dashboard per service, avoid too many panels, use consistent units, set meaningful alert thresholds, use template variables for multi-environment views."},
        {"id": "devops-mon-4", "question": "Explain the ELK stack for log management.", "keywords": ["Elasticsearch", "Logstash", "Kibana", "log", "index", "pipeline", "search", "Filebeat"], "model_answer": "ELK Stack: Elasticsearch (search/analytics engine, stores logs as documents), Logstash (data processing pipeline - ingest, transform, output), Kibana (visualization/search UI). Modern addition: Beats (lightweight shippers - Filebeat for logs, Metricbeat for metrics). Flow: application logs -> Filebeat (ships) -> Logstash (parse, enrich, filter) -> Elasticsearch (index, store) -> Kibana (search, visualize, dashboard). Alternatives: Loki+Grafana, Datadog, Splunk."},
        {"id": "devops-mon-5", "question": "How do you set up effective alerting?", "keywords": ["alert", "threshold", "SLA", "SLO", "on-call", "escalation", "fatigue", "actionable", "severity"], "model_answer": "Effective alerting: define SLOs (Service Level Objectives) based on user experience, alert on SLO breaches not individual metrics, use multi-window/multi-burn-rate alerts to reduce noise. Severity levels: P1 (page immediately), P2 (respond within hours), P3 (next business day). Reduce alert fatigue: every alert must be actionable, include runbook links, tune thresholds regularly, group related alerts, use escalation policies (PagerDuty, OpsGenie). Review alert quality weekly."},
    ],
}


def get_topic_questions(topic_id):
    """Get 5 assessment questions for a topic."""
    questions = TOPIC_QUESTIONS.get(topic_id, [])
    return questions


def get_all_topic_ids_with_questions():
    """Get list of topic IDs that have questions available."""
    return list(TOPIC_QUESTIONS.keys())
